name: tontinemoney

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: tontine
      POSTGRES_PASSWORD: tontine
      POSTGRES_DB: tontinemoney
    ports: ['5432:5432']
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./infrastructure/docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U tontine -d tontinemoney']
      interval: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports: ['6379:6379']
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      retries: 10

  redpanda:
    image: redpandadata/redpanda:v24.2.7
    command:
      - redpanda start
      - --smp 1
      - --memory 512M
      - --overprovisioned
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
    ports: ['19092:19092']

  minio:
    image: minio/minio:latest
    command: server /data --console-address ':9001'
    environment:
      MINIO_ROOT_USER: minio-dev
      MINIO_ROOT_PASSWORD: minio-dev-secret
    ports: ['9000:9000', '9001:9001']
    volumes: [miniodata:/data]

  minio-init:
    image: minio/mc:latest
    depends_on: [minio]
    entrypoint: >
      /bin/sh -c "sleep 3; mc alias set local http://minio:9000 minio-dev minio-dev-secret &&
      mc mb --ignore-existing local/kyc-documents && mc anonymous set none local/kyc-documents"

  mailpit:
    image: axllent/mailpit:latest
    ports: ['1025:1025', '8025:8025']

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.111.0
    command: ['--config=/etc/otel/config.yaml']
    volumes:
      - ./infrastructure/monitoring/otel-collector.yaml:/etc/otel/config.yaml:ro
    ports: ['4318:4318']

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./infrastructure/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    extra_hosts: ['host.docker.internal:host-gateway']
    ports: ['9090:9090']

  grafana:
    image: grafana/grafana:latest
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
    volumes:
      - ./infrastructure/monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./infrastructure/monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    ports: ['3001:3000']

volumes:
  pgdata:
  miniodata:
