global:
  scrape_interval: 15s
scrape_configs:
  - job_name: tontinemoney-api
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:4000']
  - job_name: api-gateway
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8080']
  - job_name: payment-gateway
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8090']
